### ISSUE TITLE
The 'e' character closes the menu when changing Moloch's name

### ISSUE THREAD

**Issue by ramou** [Concordia-Modding-Community/moloch#1]
I've seen this in other mods and can't confirm it consistently does it in all environments, but it's certainly a thing. Probably need to capture and hold keyEvents or whatnot while the UI is open.

**Comment by alexandre-lavoie** [comment]
abce98e seems to have fixed this - though it doesn't really consider if a player decides to change key bindings. This said - I don't think this matters for CTRL, Shift, and ESC.
