### ISSUE TITLE
Progression System

### ISSUE THREAD

**Issue by ramou** [Concordia-Modding-Community/moloch#2]
Have a tab (accessible with operator key) that allows the specification of requirements for each stage of Moloch. Give a default duration of 7 days before Moloch becomes angry. Allow up to three items with amounts (meaning you could have moloch demand a stack of otherwise unstackable things, say 62 cakes). This implies that moloch should consume items as they come in, not waiting for a complete stack.

While it would be nice to be able to quickly re-order, let's leave that for now. Just being able to add a few of these for progression is the immediate goal.

**Comment by alexandre-lavoie** [comment]
I currently don't have any idea in mind for a non-hacky solution to allow stacks to go past their limit. I'll have a look at how other mods do it - but for the short term - I will assume vanilla stacks.

**Comment by ramou** [comment]
Between the two of us, we have a working system that can be managed through the use of `/data` commands (for now) with a working client GUI that is of solid quality. I'll close this ticket pending more specific issue being brought once people get a chance to use it and we see what they really want.
