### ISSUE TITLE
There are no source attachments in the reference libraries

### ISSUE THREAD

**Issue by ramou** [Concordia-Modding-Community/moloch#4]
This is particularly painful for forge. Is this a matter of Gradle configuration, or has the forge project stopped shipping source?

**Comment by alexandre-lavoie** [comment]
I believe this is intentional - or an Eclipse related issue?

**Comment by ramou** [comment]
@nicwatson pointed out that there is an expectation to run `.\gradlew eclipse` in the powershell, separately from running the thing that creates the run tasks in the workspace.
